name: Build Havoc Client
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          modules: 'qtbase qtdeclarative qttools'

      - name: Build Havoc Client
        shell: pwsh
        run: |
          cd Client
          cmake -B build -DCMAKE_PREFIX_PATH="${{ env.Qt6_Dir }}"
          cmake --build build --config Release
